version: '3.8'

services:
  web:
    build: .
   # command: #gunicorn screencast.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/kc/
      - static:/usr/src/kc/static/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kcadmin
      - POSTGRES_PASSWORD=letsgooooo
      - POSTGRES_DB=kcdata

volumes:
  postgres_data:
  static: